api_platform:
    title: 'Plateforme EBS API'
    description: 'List of Plateforme EBS API endpoints. Most of them require to be logged.'

    # The version of the API.
    version: '%app_version%'

    openapi:
        # The contact information for the exposed API.
        contact:
            # The identifying name of the contact person/organization.
            name: APES
            # The URL pointing to the contact information. MUST be in the format of a URL.
            url: http://www.apes-hdf.org/page-96-0-0.html
            # The email address of the contact person/organization. MUST be in the format of an email address.
            email: contact@apes-hdf.org
        # A URL to the Terms of Service for the API. MUST be in the format of a URL.
        termsOfService: https://github.com/ApesHDF/EBS/blob/main/LICENSE  
        # The license information for the exposed API.
        license:
            # The license name used for the API.
            name: MIT
            # URL to the license used for the API. MUST be in the format of a URL.
            url: https://github.com/ApesHDF/EBS/blob/main/LICENSE
