framework:
    messenger:
        # https://symfony.com/doc/current/messenger/multiple_buses.html
        default_bus: command.bus
        buses:
            query.bus:   # $queryBus
            command.bus: # $commandBus
    
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            sync: 'sync://'
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            failed: '%env(MESSENGER_TRANSPORT_DSN)%?queue_name=failed'

        routing:
            # Sync
            '*': sync # default routing for all messages until not changed             

            # Route your messages to the transports
            # Async
            # 'App\Message\YourMessage': async

when@test:
    framework:
        messenger:
            transports:
                # replace with your transport name here (e.g., my_transport: 'in-memory://')
                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
                async: 'test://'
                # sync: 'test://'
