# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app_version: 0.7.2
    brand: PlateformCoop

    # https://symfony.com/doc/current/performance.html#dump-the-service-container-into-a-single-file
    container.dumper.inline_factories: true

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            string $appEnv: '%kernel.environment%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'            

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # to have i18n codes instead of real texts (like the test env), uncomment this
#    App\Translator\NoTranslator:
#        decorates: translator
#        arguments:
#            - '@App\Translator\NoTranslator.inner'

    App\Geocoder\GeoProviderInterface: 
        alias: App\Geocoder\GeoProvider

when@test:
    services:
        # Disable the translations to test on codes instead of the translated texts
        App\Translator\NoTranslator:
            decorates: translator
            arguments:
                - '@App\Translator\NoTranslator.inner'

        # Mock geocoder calls in test env, comment this to make actual HTTP calls
        # to the Geocoder services.
        App\Tests\Mock\Geocoder\GeoProviderMock:
            decorates: 'App\Geocoder\GeoProvider' 
