apiVersion: v1
kind: Secret
metadata:
  name: {{ include "plateforme-ebs" . }}
  labels:
    {{- include "plateforme-ebs.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.cnpg.enabled }}
  database-url: {{ printf "postgresql://%s:%s@%s-rw/%s?serverVersion=%s&charset=utf8" .Values.cnpg.owner (.Values.cnpg.credentials.password | urlquery) (include "plateforme-ebs.cnpgClusterName" .) .Values.cnpg.database .Values.cnpg.postgresql.version | b64enc | quote }}
  cnpg-password: {{ .Values.cnpg.credentials.password | b64enc | quote }}
  {{- else }}
  database-url: {{ .Values.postgresql.url | b64enc | quote }}
  {{- end }}
  php-app-secret: {{ .Values.php.appSecret | default (randAlphaNum 40) | b64enc | quote }}
  php-jwt-passphrase: {{ .Values.php.jwt.passphrase | b64enc | quote }}
  php-jwt-public-key: {{ .Values.php.jwt.publicKey | b64enc | quote }}
  php-jwt-secret-key: {{ .Values.php.jwt.secretKey | b64enc | quote }}
  mercure-jwt-secret: {{ .Values.mercure.jwtSecret | default (randAlphaNum 40) | b64enc | quote }}
  {{- if .Values.maildev.enabled }}
  mailer-dsn: {{ printf "smtp://%s:%s" ( include "maildev.fullname" .Subcharts.maildev ) "1025" | b64enc | quote }}
  {{- else }}
  mailer-dsn: {{ .Values.mailer.dsn | b64enc | quote }}
  {{- end }}
  sms-dsn: {{ .Values.sms.dsn | b64enc | quote }}
  payum-apikey: {{ .Values.payum.apikey | b64enc | quote }}
  php-storage-key: {{ .Values.php.storage.key | default "" | b64enc | quote }}
  php-storage-secret: {{ .Values.php.storage.secret | default "" | b64enc | quote }}