# additional services related to Doctrine
services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Needed to activate autowiring for the Doctrine listener
    App\Doctrine\Listener\:
        resource: '../../src/Doctrine/Listener'
        tags:
            - { name: doctrine.orm.entity_listener }
